version: '3.7'
services:
  nginx:
    image: ghcr.io/dmitrydeco/portainer-test-nginx:latest
    working_dir: /www
    command: [nginx-debug, '-g', 'daemon off;']
    stop_grace_period: 20s
    healthcheck:
      test: "netstat -an | grep :80"
      interval: 20s
      timeout: 5s
      retries: 3
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
        order: start-first
    ports:
      - "5401:80"
